fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # This one has been added to fail fast on syntax errors
      # before running expensive pylint
      - id: check-ast
        types_or:
          - python
          - pyi
        exclude: "/(site-packages|development-[^/]*|docs|node_modules|__pycache__|\\..*)/$"
      - id: check-json
      - id: check-yaml
        types: [file]
        files: \.(yaml|yml)$
  - repo: https://github.com/koalaman/shellcheck-precommit.git
    rev: v0.10.0
    hooks:
      - id: shellcheck
        #args: [--format,json]
        stages: [manual]
  - repo: local
    hooks:
      - id: pylint
        name: Local PyLint
        language: system
        require_serial: true
        types:
          - python
        exclude: "^[^/]*env/|dev-[^/]*/|docs/"
        entry: pylint
        args: [--source-roots, .]
      - id: mypy
        name: Local MyPy
        language: system
        types_or:
          - python
          - pyi
        exclude: "/(site-packages|development-[^/]*|docs|node_modules|__pycache__|\\..*)/$"
        require_serial: true
        entry: mypy
        args: [--strict, --show-error-codes, --no-warn-unused-ignores]
      - id: pip-audit-local
        name: pip-audit over local environment
        stages: [manual]
        language: system
        always_run: true
        pass_filenames: false
        require_serial: true
        entry: pip-audit
        args: []

  - repo: https://github.com/jmfernandez/pre-commit_mirrors-actionlint.git
    rev: v1.7.1
    hooks:
      - id: actionlint

  - repo: https://github.com/ambv/black.git
    rev: 23.3.0
    hooks:
      - id: black
        name: black_apply
        exclude: "^[^/]*env/|development-[^/]*/|docs/"
        stages: [manual]
      - id: black
        exclude: "^[^/]*env/|development-[^/]*/|docs/"
        args: [--diff, --check]

  - repo: https://github.com/pypa/pip-audit
    rev: v2.7.3
    hooks:
      - id: pip-audit
        stages: [manual]
        args: ["-r", "requirements.txt"]